### ISSUE TITLE
Link to look at the Validation online

### ISSUE THREAD

**Issue by KaanBaylan** [rstropek-teaching/form-validation-quiz-4ahif-KaanBaylan#1]
Dear Prof. Stropek,

here is the link to my solution of the validation form:

https://cdn.rawgit.com/rstropek-teaching/form-validation-quiz-4ahif-KaanBaylan/bd8de4f7/dist/index.html

Yours faithfully,
Baylan Kaan, 4AHIF

**Comment by rstropek** [comment]
Well done, works as expected 👍 Your extra point is secured.

Just one thing: Don't repeat yourself. You have pieces of code that appear nearly identical multiple times in your codebase. You could create helper functions for that logic.

Greetings,
Rainer Stropek.
